### ISSUE TITLE
Typo in Title

### ISSUE THREAD

**Issue by xdeama** [motamed/LG-UltraFine-Brightness-Control#4]
Thank you for sharing this incredible small piece of software that made my day. I've found and tested a dozen other tools to change brightness with Windows 10 on a Lenovo X1 connected via Thunderbolt to a LG Ultrafine 5K and none of them worked. Your tool works absolutely fine and instantly on model number 27MD5KL-B.AEU.

I used the fact that I found a minor typo in the title (t missing form Ultra)
![image](https://user-images.githubusercontent.com/74056296/107266651-1a834e80-6a46-11eb-8d9b-489c6ff1391b.png)

to say THANK YOU!!!!! <3

**Comment by motamed** [comment]
Glad it worked for you 😀
Feel free to do a pull request so you can be a contributor if you would like to 😄
