### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by yourjelly** [motamed/LG-UltraFine-Brightness-Control#5]
![Screen Snip of error](https://user-images.githubusercontent.com/26312697/148634393-6fb453cb-0b75-4a72-ac36-34180d5f2031.png)

Not sure what's the cause.

**Comment by yourjelly** [comment]
In case anyone else is searching for this it turns out LG finally released official windows drivers anyway in November 2021

**Comment by xdeama** [comment]
Amazing they really did! Still don’t trust them to maintain it for long. Please don’t close down and delete this project 🙂.
